/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.protocols.json;

import software.amazon.awssdk.annotations.SdkProtectedApi;

/**
 * Implemented by generated model classes whose members all bind to the payload of a JSON-family protocol
 * (AWS-JSON, REST-JSON, CBOR, RPCv2-CBOR), allowing the shape to write its own fields with straight-line
 * generated code instead of the generic {@code SdkField} reflection loop.
 *
 * <p>The JSON protocol marshaller dispatches to {@link #marshallJsonFields} whenever a POJO implements
 * this interface; shapes generated by older SDK versions (or shapes with non-payload members) fall back
 * to the generic loop. Generated implementations must produce bytes identical to the generic loop.
 */
@SdkProtectedApi
public interface StructuredJsonWritable {

    /**
     * Writes this object's payload-bound fields to the generator. The caller is responsible for the
     * surrounding {@code writeStartObject()}/{@code writeEndObject()} calls.
     *
     * @param generator the generator for the wire format being marshalled (JSON text or CBOR).
     */
    void marshallJsonFields(StructuredJsonGenerator generator);
}
